export { default as Hero } from "./hero/Hero"
export { default as Navbar } from "./navbar/Navbar"
export { default as Sidebar } from "./sidebar/Sidebar"
export { default as Parallex } from "./parallex/Parallex"
export { default as Services } from "./services/Services"
export { default as Portfolio } from "./portfolio/Portfolio"
export { default as Contact } from "./contact/Contact"